
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: ui-backend
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: ui-backend-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: ui-backend
    app.kubernetes.io/part-of: ui-backend
    app.kubernetes.io/managed-by: kustomize
  name: manager-metrics-monitor
  namespace: projectsveltos
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: ui-backend
