apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: ui-backend
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: ui-backend-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: ui-backend
    app.kubernetes.io/part-of: ui-backend
    app.kubernetes.io/managed-by: kustomize
  name: manager-metrics-service
  namespace: projectsveltos
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: ui-backend
