name: main
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  build-static-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.23.4
    - name: Build
      run: make build
    - name: FMT
      run: make fmt
    - name: VET
      run: make vet
    - name: LINT
      run: make lint
      env:
        LINT: true
  build-ut:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.23.4
    - name: ut
      run: make test
      env:
        UT: true
  FV:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.23.4
    - name: fv
      run: make create-cluster fv
      env:
        FV: true